<?php
/**
 * @package     com_handover
 *
 * @author      Pieter-Jan de Vries/Obix webtechniek <pieter@obix.nl>
 * @copyright   Copyright (C) 2024+ Obix webtechniek. All rights reserved.
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * @link        https://www.obix.nl
 */

namespace Obix\Component\Handover\Administrator\Extension\Package\Manifest;

\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Uri\Uri;
use Obix\Component\Handover\Administrator\Extension\Joomla\ComponentHelper;
use Obix\Component\Handover\Administrator\Extension\Settings;

class PackageManifestAttributes implements ManifestAttributesInterface
{
    private string $version;

    /**
     * @param Settings $version
     */
    public function __construct(string $version = '1.0.0')
    {
        $this->version = $version;
    }

    public function getAttributes(): array
    {
        $appConfig = Factory::getApplication()->getConfig();
        
        $componentVersion = ComponentHelper::getComponentVersion('com_handover');
        
        return [
            'creationDate' => (new \DateTimeImmutable())->format('Y-m-d'),
            'author' => $appConfig->get('sitename'),
            'authorEmail' => $appConfig->get('mailfrom'),
            'authorUrl' => Uri::root(),
            'copyright' => '(C) ' . (new \DateTimeImmutable())->format('Y') . ', ' . Factory::getApplication(
                )->getConfig()->get('sitename'),
            'license' => 'GNU General Public License version 2 or later',
            'version' => $this->version,
            'description' => 'Import files generated by Handover.',
            'componentPackage' => 'com_handover-' . $componentVersion . '.zip',
            'filesPackage' => 'handover_import_files-' . $this->version . '.zip'
        ];
    }
}