<?php
/**
 * @package     com_handover
 *
 * @author      Pieter-Jan de Vries/Obix webtechniek <pieter@obix.nl>
 * @copyright   Copyright (C) 2024+ Obix webtechniek. All rights reserved.
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * @link        https://www.obix.nl
 */

namespace Obix\Component\Handover\Administrator\Model;

\defined('_JEXEC') or die;

use Joomla\Component\Categories\Administrator\Helper\CategoriesHelper;
use Joomla\Component\Categories\Administrator\Model\CategoriesModel as BaseCategoriesModel;

class CategoriesModel extends BaseCategoriesModel
{
    public function getItems()
    {
        $items = parent::getItems(); // TODO: Change the autogenerated stub

        foreach ($items as &$item) {
            $item->associations = [];

            foreach (CategoriesHelper::getAssociations($item->id, $item->extension) as $lang => $association) {
                [$associationId, $associationAlias] = explode(':', $association, 2);
                $item->associations[$lang] = $associationId;
            }
        }

        return $items;
    }

    public function getListQuery()
    {
        $db    = $this->getDatabase();

        $subQuery = $db->getQuery(true)
            ->select('DISTINCT ' . $db->quoteName('category_id'))
            ->from($db->quoteName('#__fields_categories'));

        $query = parent::getListQuery();
        $query->select('\'{}\' AS associations');
        $query->join(
            'INNER',
            '(' . $subQuery . ') AS ' . $db->quoteName('fg'),
            $db->quoteName('fg.category_id') . ' = ' . $db->quoteName('a.id')
        );

        return $query;
    }
}