<?php
/**
 * @package     com_hopper
 *
 * @author      Pieter-Jan de Vries/Obix webtechniek <pieter@obix.nl>
 * @copyright   Copyright (C) 2024+ Obix webtechniek. All rights reserved.
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * @link        https://www.obix.nl
 */

namespace Obix\Component\Hopper\Administrator\Extension\Package\Manifest;

\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Uri\Uri;
use Obix\Component\Hopper\Administrator\Extension\Settings;

class FilesManifestAttributes implements ManifestAttributesInterface
{
    private string $version;

    private Settings $settings;

    /**
     * @param Settings $version
     */
    public function __construct(Settings $settings, string $version = '1.0.0')
    {
        $this->settings = $settings;
        $this->version = $version;
    }

    public function getAttributes(): array
    {
        $appConfig = Factory::getApplication()->getConfig();

        return [
            'creationDate' => (new \DateTimeImmutable())->format('Y-m-d'),
            'author' => $appConfig->get('sitename'),
            'authorEmail' => $appConfig->get('mailfrom'),
            'authorUrl' => Uri::root(),
            'copyright' => '(C) ' . (new \DateTimeImmutable())->format('Y') . ', ' . Factory::getApplication(
                )->getConfig()->get('sitename'),
            'license' => 'GNU General Public License version 2 or later',
            'version' => $this->version,
            'description' => 'Import files generated by Hopper.',
            'filesTarget' => str_replace(JPATH_ROOT . '/', '', $this->settings->importFolder($this->version)),
            'filesFolder' => basename($this->settings->importFilesFolder($this->version))
        ];
    }
}