<?php
/**
 * @package     com_hopper
 *
 * @author      Pieter-Jan de Vries/Obix webtechniek <pieter@obix.nl>
 * @copyright   Copyright (C) 2024+ Obix webtechniek. All rights reserved.
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * @link        https://www.obix.nl
 */

namespace Obix\Component\Hopper\Administrator\Extension\Package\Manifest;

defined('_JEXEC') or die;

use DateTimeImmutable;
use Joomla\CMS\Factory;
use Joomla\CMS\Uri\Uri;
use Obix\Component\Hopper\Administrator\Extension\Joomla\ComponentHelper;
use Obix\Component\Hopper\Administrator\Extension\PackageHelper;

use function defined;

class PackageManifestAttributes implements ManifestAttributesInterface
{
    private PackageHelper $packageHelper;

    /**
     * @param PackageHelper $version
     */
    public function __construct(PackageHelper $packageHelper)
    {
        $this->packageHelper = $packageHelper;
    }

    public function getAttributes(): array
    {
        $appConfig = Factory::getApplication()->getConfig();

        $componentVersion = ComponentHelper::getComponentVersion('com_hopper');

        return [
            'packagename' => $this->packageHelper->getProjectAlias(),
            'creationDate' => (new DateTimeImmutable())->format('Y-m-d'),
            'author' => $appConfig->get('sitename'),
            'authorEmail' => $appConfig->get('mailfrom'),
            'authorUrl' => Uri::root(),
            'copyright' => '(C) ' . (new DateTimeImmutable())->format('Y') . ', ' . Factory::getApplication(
                )->getConfig()->get('sitename'),
            'license' => 'GNU General Public License version 2 or later',
            'version' => $this->packageHelper->getVersion(),
            'description' => 'Import files generated by Hopper.',
            'componentPackage' => $this->packageHelper->componentPackageName($componentVersion),
            'filesPackage' => $this->packageHelper->filesPackageName()
        ];
    }
}